### ISSUE TITLE
Read PGN from local file

### ISSUE THREAD

**Issue by HBiSoft** [jj30/ChessPGNHelper#1]
Is it possible to read a PGN from a file on my device instead of getting it from a API?

Also, I was not able to fetch any games , by searching for them, I don't know if your API is still available.

**Comment by jj30** [comment]
It was discontinued at about the time you wrote your post. 

I was paying for hosting for several apps. Also, Google changed their own AdMob requirements, then flagged me for violating them, so the app itself is currently banned from the playstore.

Short-term vision includes exactly what you wrote, plus, in addition, I want to be able to read from a USB. I may get to this before too long, now.

**Comment by jj30** [comment]
@HBiSoft Moving over to https://github.com/jj30/PGNHelperKotlin

I will release it to the play store, but Google makes everything difficult, you know.

**Comment by jj30** [comment]
You may now read PGNs from a mounted USB!

The PGNs must be in the root folder, and the USB must not be self-powered (USB Host instead of USB Accessory).

Am closing this issue now.

Play store link:

https://play.google.com/store/apps/details?id=bldg5.jj.pgnbase
